config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#show'

  resources :users, only: [:index, :show] do
    resources :items, only: [:new, :create, :destroy]
  end

  get 'home' => 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :user, presence: true

  default_scope { order('created_at ASC') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :firstname, :lastname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :firstname, :lastname])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = 'Item was saved.'
      redirect_to root_path
    else
      flash.now[:alert] = 'There was an error saving the post. Please try again.'
      redirect_to root_path
       end
     end

  def destroy
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "\"#{@item.name}\" has been successfully completed!"
      redirect_to root_path
    else
      flash.now[:alert] = 'There was an error removing the item.'
      render root_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = if params[:id].nil?
              current_user
            else
              User.find(params[:id])
                                end
    @items = @user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<br>
<div class='container'>
  <div class="jumbotron center-align">
    <h1 class='shadow'>Blocitoff</h1>
    <h3>A self-destructing to-do list to keep you focused on the things that really matter.</h3>
  </div>
</div>

app/views/items/_form.html.erb
<h4>Add a New Item</h4>
<%= form_for [user, item] do |f| %>
<div class="form-group">
  <%= f.label :name, class: 'sr-only' %>
  <%= f.text_field :name, class: 'form-control', placeholder: "Enter a new to-do item" %>
</div>
<%= f.submit "Save", class: 'btn btn-default pull-right' %>
<% end %>

app/views/items/_item.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-9'>
      <ul>
        <li>
          <strong><%= item.name %></strong>
        </li>
        <div class="media-body">
          <small>
            created
            <%= time_ago_in_words(item.created_at) %>
            ago</small>
        </div>
      </ul>
    </div>
    <% if current_user == @user %>
    <div class='col-md-3'>
      Mark as Completed:
      <%= link_to "", user_item_path(@user, item.id), method: :delete, class: 'glyphicon glyphicon-ok' %></div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocitoff", home_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <div class="pull-right user-info">
          <% if user_signed_in? %>
          Signed in as:
          <strong><%= link_to current_user.username, user_path(current_user) %></strong>
          |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
          -
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
          -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </ul>
      </div>

      <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
      <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<div class='container'>
  <h1>Users:</h1>

  <div class="row">
    <div class='col-md-8'>
      <% @users.each do |user| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to "#{user.firstname} #{user.lastname}", user_path(user.id) %>
          </h4>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class='header'>
    <%= @user.firstname %>
    <%= @user.lastname %>
  </h1>
  <div class='center'>
    <h4>Username:
      <%= @user.username %>
    </h4>
    <h5>
      <%= @user.email %></h5>
  </div>
  <div>
    <h3 class='altheader'>To-Do</h3>
    <% if @user.items.empty? %>
    <h4 class='center'>There are no to-do items on the list.</h4>
  <% else %>
    <%= render @user.items %>
    <% end %>
  </div>
  <br>
  <% if current_user == @user %>
  <%= render 'items/form', item: Item.new, user: @user %>
  <% end %>
</div>